
version: "3"
services:
  client:
    container_name: web_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: meetup-app/client
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./client
    links:
      - api
  api:
    container_name: web_api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: meetup-app/api
    ports:
      - "1234:1234"
    expose:
      - "1234"
    volumes:
      - ./api